# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "alert_game_completed" ("id" SERIAL NOT NULL PRIMARY KEY,"recipient_id" BIGINT NOT NULL,"consented" BOOLEAN NOT NULL,"creation_date" TIMESTAMP NOT NULL,"game_id" BIGINT NOT NULL,"teacher_points" INTEGER NOT NULL,"students_points" INTEGER NOT NULL,"quiz_id" BIGINT NOT NULL);
create index "alert_game_completed__name_index" on "alert_game_completed" ("recipient_id","consented");
create table "answer_id" ("id" SERIAL NOT NULL PRIMARY KEY,"dummy" SMALLINT NOT NULL);
create table "application_users" ("user_id" BIGINT NOT NULL PRIMARY KEY,"consented" BOOLEAN NOT NULL,"name" VARCHAR(254) NOT NULL,"allow_auto_match" BOOLEAN NOT NULL,"seen_help" BOOLEAN NOT NULL,"email_updates" BOOLEAN NOT NULL,"last_access" TIMESTAMP NOT NULL);
create index "application_users__name_index" on "application_users" ("name");
create table "courses" ("id" SERIAL NOT NULL PRIMARY KEY,"name" VARCHAR(254) NOT NULL,"organization" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"edit_code" VARCHAR(254) NOT NULL,"view_code" VARCHAR(254),"creation_Date" TIMESTAMP NOT NULL,"update_date" TIMESTAMP NOT NULL);
create table "courses_2_quizzes" ("course_id" BIGINT NOT NULL,"quiz_id" BIGINT NOT NULL,"start_date" TIMESTAMP,"end_date" TIMESTAMP);
alter table "courses_2_quizzes" add constraint "courses_2_quizzes__pk" primary key("course_id","quiz_id");
create table "derivative_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"mathml" VARCHAR(254) NOT NULL,"rawstr" VARCHAR(254) NOT NULL,"comment" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "derivative_graph_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"derivative_order" VARCHAR(254) NOT NULL,"comment" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "derivative_graph_question_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "derivative_graph_question_2_quiz__question_index" on "derivative_graph_question_2_quiz" ("id");
create index "derivative_graph_question_2_quiz__quiz_index" on "derivative_graph_question_2_quiz" ("quiz");
create table "derivative_graph_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"mathml" VARCHAR(254) NOT NULL,"rawstr" VARCHAR(254) NOT NULL,"show_function" BOOLEAN NOT NULL,"creation_date" TIMESTAMP NOT NULL,"derivativeOrder" VARCHAR(254) NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "derivative_question_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "derivative_question_2_quiz__question_index" on "derivative_question_2_quiz" ("id");
create index "derivative_question_2_quiz__quiz_index" on "derivative_question_2_quiz" ("quiz");
create table "derivative_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"mathml" VARCHAR(254) NOT NULL,"rawstr" VARCHAR(254) NOT NULL,"creation_date" TIMESTAMP NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "friends" ("user_id" BIGINT NOT NULL,"friend_id" BIGINT NOT NULL,"request_date" TIMESTAMP,"accept_date" TIMESTAMP);
alter table "friends" add constraint "friends__primary_key" primary key("user_id","friend_id");
create table "games" ("id" SERIAL NOT NULL PRIMARY KEY,"request_date" TIMESTAMP NOT NULL,"requestor" BIGINT NOT NULL,"requestor_skill" DOUBLE PRECISION NOT NULL,"requestee" BIGINT NOT NULL,"requestee_skill" DOUBLE PRECISION NOT NULL,"response" SMALLINT NOT NULL,"course" BIGINT,"requestor_quiz" BIGINT,"requestor_quiz_done" BOOLEAN NOT NULL,"requestee_quiz" BIGINT,"requestee_quiz_done" BOOLEAN NOT NULL,"requestee_finished" BOOLEAN NOT NULL,"requestor_finished" BOOLEAN NOT NULL,"requestee_student_points" INTEGER,"requestee_teacher_points" INTEGER,"requestor_student_points" INTEGER,"requestor_teacher_points" INTEGER,"finished_date" TIMESTAMP);
create table "graph_match_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"guess_index" SMALLINT NOT NULL,"comment" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "graph_match_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"function1Math" VARCHAR(254) NOT NULL,"function1Raw" VARCHAR(254) NOT NULL,"function2Math" VARCHAR(254) NOT NULL,"function2Raw" VARCHAR(254) NOT NULL,"function3Math" VARCHAR(254) NOT NULL,"function3Raw" VARCHAR(254) NOT NULL,"graphThis" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "graph_match_questions_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "graph_match_question_2_quiz__question_index" on "graph_match_questions_2_quiz" ("id");
create index "graph_match_question_2_quiz__quiz_index" on "graph_match_questions_2_quiz" ("quiz");
create table "multiple_choice_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"guess_index" SMALLINT NOT NULL,"comment" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "multiple_choice_question_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "multiple_choice_question_2_quiz__question_index" on "multiple_choice_question_2_quiz" ("id");
create index "multiple_choice_question_2_quiz__quiz_index" on "multiple_choice_question_2_quiz" ("quiz");
create table "multiple_choice_question_options" ("id" SERIAL NOT NULL PRIMARY KEY,"question_id" BIGINT NOT NULL,"option" VARCHAR(254) NOT NULL);
create table "multiple_choice_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"description" VARCHAR(254) NOT NULL,"explanation" VARCHAR(254) NOT NULL,"correct_answer" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "multiple_function_answer_options" ("id" SERIAL NOT NULL PRIMARY KEY,"answer_id" BIGINT NOT NULL,"mathml" VARCHAR(254) NOT NULL,"rawstr" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL);
create table "multiple_function_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"comment" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "multiple_function_question_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "multiple_function_question_2_quiz__question_index" on "multiple_function_question_2_quiz" ("id");
create index "multiple_function_question_2_quiz__quiz_index" on "multiple_function_question_2_quiz" ("quiz");
create table "multiple_function_question_options" ("id" SERIAL NOT NULL PRIMARY KEY,"question_id" BIGINT NOT NULL,"option" VARCHAR(254) NOT NULL,"mathml" VARCHAR(254) NOT NULL,"rawstr" VARCHAR(254) NOT NULL);
create table "multiple_function_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"description" VARCHAR(254) NOT NULL,"explanation" VARCHAR(254) NOT NULL,"creation_date" TIMESTAMP NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "organizations" ("id" SERIAL NOT NULL PRIMARY KEY,"name" VARCHAR(254) NOT NULL,"creation_Date" TIMESTAMP NOT NULL,"update_date" TIMESTAMP NOT NULL);
create table "polynomial_zone_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"zones" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"comment" VARCHAR(254) NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "polynomial_zone_question_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "polynomial_zone_question_2_quiz__question_index" on "polynomial_zone_question_2_quiz" ("id");
create index "polynomial_zone_question_2_quiz__quiz_index" on "polynomial_zone_question_2_quiz" ("quiz");
create table "polynomial_zone_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"roots" VARCHAR(254) NOT NULL,"scale" DOUBLE PRECISION NOT NULL,"zone_type" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "question_id" ("id" SERIAL NOT NULL PRIMARY KEY,"dummy" SMALLINT NOT NULL);
create table "quizzes" ("id" SERIAL NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"name" VARCHAR(254) NOT NULL,"creation_date" TIMESTAMP NOT NULL,"update_date" TIMESTAMP NOT NULL);
create table "secure_social_logins" ("id" SERIAL NOT NULL PRIMARY KEY,"user_id" VARCHAR(254) NOT NULL,"provider_id" VARCHAR(254) NOT NULL,"first_name" VARCHAR(254) NOT NULL,"last_name" VARCHAR(254) NOT NULL,"full_name" VARCHAR(254) NOT NULL,"email" VARCHAR(254),"avatar_url" VARCHAR(254),"auth_Method" VARCHAR(254) NOT NULL,"token" VARCHAR(254),"secret" VARCHAR(254),"access_token" VARCHAR(254),"token_type" VARCHAR(254),"expires_in" INTEGER,"refresh_token" VARCHAR(254),"hasher" VARCHAR(254),"password" VARCHAR(254),"salt" VARCHAR(254),"creation_date" TIMESTAMP NOT NULL,"update_date" TIMESTAMP NOT NULL);
create table "secure_social_tokens" ("uuid" VARCHAR(254) NOT NULL PRIMARY KEY,"email" VARCHAR(254) NOT NULL,"creation_time" TIMESTAMP NOT NULL,"expiration_time" TIMESTAMP NOT NULL,"is_sign_up" BOOLEAN NOT NULL);
create table "tangent_answers" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"question_id" BIGINT NOT NULL,"slope_mathml" VARCHAR(254) NOT NULL,"slope_rawstr" VARCHAR(254) NOT NULL,"intercept_mathml" VARCHAR(254) NOT NULL,"intercept_rawstr" VARCHAR(254) NOT NULL,"comment" VARCHAR(254) NOT NULL,"correct" SMALLINT NOT NULL,"creation_date" TIMESTAMP NOT NULL);
create table "tangent_question_2_quiz" ("id" BIGINT NOT NULL,"quiz" BIGINT NOT NULL,"owner" BIGINT NOT NULL,"creation_date" TIMESTAMP NOT NULL,"order" INTEGER NOT NULL);
create index "tangent_question_question_2_quiz__question_index" on "tangent_question_2_quiz" ("id");
create index "tangent_question_question_2_quiz__quiz_index" on "tangent_question_2_quiz" ("quiz");
create table "tangent_questions" ("id" BIGINT NOT NULL PRIMARY KEY,"owner" BIGINT NOT NULL,"function" VARCHAR(254) NOT NULL,"function_str" VARCHAR(254) NOT NULL,"at_point_x" VARCHAR(254) NOT NULL,"at_point_x_str" VARCHAR(254) NOT NULL,"creation_date" TIMESTAMP NOT NULL,"at_creation_difficulty" DOUBLE PRECISION NOT NULL,"order" INTEGER NOT NULL);
create table "users_2_courses" ("user_id" BIGINT NOT NULL,"course_id" BIGINT NOT NULL,"access" SMALLINT NOT NULL,"section" INTEGER NOT NULL);
alter table "users_2_courses" add constraint "users_2_courses_pk" primary key("user_id","course_id");
create table "users_2_quizzes" ("user_id" BIGINT NOT NULL,"quiz_id" BIGINT NOT NULL,"access" SMALLINT NOT NULL);
alter table "users_2_quizzes" add constraint "users_2_quizzes__pk" primary key("user_id","quiz_id");
alter table "alert_game_completed" add constraint "alert_game_completed__game_fk" foreign key("game_id") references "games"("id") on update NO ACTION on delete CASCADE;
alter table "alert_game_completed" add constraint "alert_game_completed__user_fk" foreign key("recipient_id") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "alert_game_completed" add constraint "alert_game_completed__quiz_fk" foreign key("quiz_id") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "application_users" add constraint "application_users__user_fk" foreign key("user_id") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "courses" add constraint "courses__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "courses" add constraint "courses__organization_fk" foreign key("organization") references "organizations"("id") on update NO ACTION on delete CASCADE;
alter table "courses_2_quizzes" add constraint "courses_2_quizzes__course_fk" foreign key("course_id") references "courses"("id") on update NO ACTION on delete CASCADE;
alter table "courses_2_quizzes" add constraint "courses_2_quizzes__quiz_fk" foreign key("quiz_id") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_answers" add constraint "derivative_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_answers" add constraint "derivative_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_answers" add constraint "derivative_answers__question_fk" foreign key("question_id") references "derivative_questions"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_answers" add constraint "derivative_graph_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_answers" add constraint "derivative_graph_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_answers" add constraint "derivative_graph_answers__question_fk" foreign key("question_id") references "derivative_graph_questions"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_question_2_quiz" add constraint "derivative_graph_question_2_quiz__question_fk" foreign key("id") references "derivative_graph_questions"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_question_2_quiz" add constraint "derivative_graph_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_questions" add constraint "derivative_graph_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_graph_questions" add constraint "derivative_graph_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_question_2_quiz" add constraint "derivative_question_2_quiz__question_fk" foreign key("id") references "derivative_questions"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_question_2_quiz" add constraint "derivative_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_questions" add constraint "derivative_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "derivative_questions" add constraint "derivative_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "friends" add constraint "friends__friend_fk" foreign key("friend_id") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "friends" add constraint "friends__user_fk" foreign key("user_id") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "games" add constraint "games__course_fk" foreign key("course") references "courses"("id") on update NO ACTION on delete CASCADE;
alter table "games" add constraint "games__requestor_fk" foreign key("requestor") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "games" add constraint "games__requestee_fk" foreign key("requestee") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "games" add constraint "games__requestor_quiz_fk" foreign key("requestor_quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "games" add constraint "games__requestee_quiz_fk" foreign key("requestee_quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_answers" add constraint "graph_match_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_answers" add constraint "graph_match_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_answers" add constraint "graph_match_answers__question_fk" foreign key("question_id") references "graph_match_questions"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_questions" add constraint "graph_match_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_questions" add constraint "graph_match_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_questions_2_quiz" add constraint "graph_match_question_2_quiz__question_fk" foreign key("id") references "graph_match_questions"("id") on update NO ACTION on delete CASCADE;
alter table "graph_match_questions_2_quiz" add constraint "graph_match_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_answers" add constraint "multiple_choice_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_answers" add constraint "multiple_choice_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_answers" add constraint "multiple_choice_answers__question_fk" foreign key("question_id") references "multiple_choice_questions"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_question_2_quiz" add constraint "multiple_choice_question_2_quiz__question_fk" foreign key("id") references "multiple_choice_questions"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_question_2_quiz" add constraint "multiple_choice_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_question_options" add constraint "multiple_choice_question_options__question_id_fk" foreign key("question_id") references "multiple_choice_questions"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_questions" add constraint "multiple_choice_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_choice_questions" add constraint "multiple_choice_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_answer_options" add constraint "multiple_function_answer_options__answer_id_fk" foreign key("answer_id") references "multiple_function_answers"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_answers" add constraint "multiple_function_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_answers" add constraint "multiple_function_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_answers" add constraint "multiple_function_answers__question_fk" foreign key("question_id") references "multiple_function_questions"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_question_2_quiz" add constraint "multiple_function_question_2_quiz__question_fk" foreign key("id") references "multiple_function_questions"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_question_2_quiz" add constraint "multiple_function_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_question_options" add constraint "multiple_function_question_options__question_id_fk" foreign key("question_id") references "multiple_function_questions"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_questions" add constraint "multiple_function_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "multiple_function_questions" add constraint "multiple_function_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_answers" add constraint "polynomial_zone_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_answers" add constraint "polynomial_zone_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_answers" add constraint "polynomial_zone_answers__question_fk" foreign key("question_id") references "polynomial_zone_questions"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_question_2_quiz" add constraint "polynomial_zone_question_2_quiz__question_fk" foreign key("id") references "polynomial_zone_questions"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_question_2_quiz" add constraint "polynomial_zone_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_questions" add constraint "polynomial_zone_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "polynomial_zone_questions" add constraint "polynomial_zone_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "quizzes" add constraint "quizzes__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_answers" add constraint "tangent_answers__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_answers" add constraint "tangent_answers__id_fk" foreign key("id") references "answer_id"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_answers" add constraint "tangent_answers__question_fk" foreign key("question_id") references "tangent_questions"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_question_2_quiz" add constraint "tangent_question_2_quiz__question_fk" foreign key("id") references "tangent_questions"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_question_2_quiz" add constraint "tangent_question_2_quiz__quiz_fk" foreign key("quiz") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_questions" add constraint "tangent_questions__owner_fk" foreign key("owner") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "tangent_questions" add constraint "tangent_questions__id_fk" foreign key("id") references "question_id"("id") on update NO ACTION on delete CASCADE;
alter table "users_2_courses" add constraint "users_2_courses__user_fk" foreign key("user_id") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;
alter table "users_2_courses" add constraint "users_2_courses__course_fk" foreign key("course_id") references "courses"("id") on update NO ACTION on delete CASCADE;
alter table "users_2_quizzes" add constraint "users_2_quizzes__quiz_fk" foreign key("quiz_id") references "quizzes"("id") on update NO ACTION on delete CASCADE;
alter table "users_2_quizzes" add constraint "users_2_quizzes__user_fk" foreign key("user_id") references "secure_social_logins"("id") on update NO ACTION on delete CASCADE;

# --- !Downs

alter table "alert_game_completed" drop constraint "alert_game_completed__game_fk";
alter table "alert_game_completed" drop constraint "alert_game_completed__user_fk";
alter table "alert_game_completed" drop constraint "alert_game_completed__quiz_fk";
alter table "application_users" drop constraint "application_users__user_fk";
alter table "courses" drop constraint "courses__owner_fk";
alter table "courses" drop constraint "courses__organization_fk";
alter table "courses_2_quizzes" drop constraint "courses_2_quizzes__course_fk";
alter table "courses_2_quizzes" drop constraint "courses_2_quizzes__quiz_fk";
alter table "derivative_answers" drop constraint "derivative_answers__owner_fk";
alter table "derivative_answers" drop constraint "derivative_answers__id_fk";
alter table "derivative_answers" drop constraint "derivative_answers__question_fk";
alter table "derivative_graph_answers" drop constraint "derivative_graph_answers__owner_fk";
alter table "derivative_graph_answers" drop constraint "derivative_graph_answers__id_fk";
alter table "derivative_graph_answers" drop constraint "derivative_graph_answers__question_fk";
alter table "derivative_graph_question_2_quiz" drop constraint "derivative_graph_question_2_quiz__question_fk";
alter table "derivative_graph_question_2_quiz" drop constraint "derivative_graph_question_2_quiz__quiz_fk";
alter table "derivative_graph_questions" drop constraint "derivative_graph_questions__owner_fk";
alter table "derivative_graph_questions" drop constraint "derivative_graph_questions__id_fk";
alter table "derivative_question_2_quiz" drop constraint "derivative_question_2_quiz__question_fk";
alter table "derivative_question_2_quiz" drop constraint "derivative_question_2_quiz__quiz_fk";
alter table "derivative_questions" drop constraint "derivative_questions__owner_fk";
alter table "derivative_questions" drop constraint "derivative_questions__id_fk";
alter table "friends" drop constraint "friends__friend_fk";
alter table "friends" drop constraint "friends__user_fk";
alter table "games" drop constraint "games__course_fk";
alter table "games" drop constraint "games__requestor_fk";
alter table "games" drop constraint "games__requestee_fk";
alter table "games" drop constraint "games__requestor_quiz_fk";
alter table "games" drop constraint "games__requestee_quiz_fk";
alter table "graph_match_answers" drop constraint "graph_match_answers__owner_fk";
alter table "graph_match_answers" drop constraint "graph_match_answers__id_fk";
alter table "graph_match_answers" drop constraint "graph_match_answers__question_fk";
alter table "graph_match_questions" drop constraint "graph_match_questions__owner_fk";
alter table "graph_match_questions" drop constraint "graph_match_questions__id_fk";
alter table "graph_match_questions_2_quiz" drop constraint "graph_match_question_2_quiz__question_fk";
alter table "graph_match_questions_2_quiz" drop constraint "graph_match_question_2_quiz__quiz_fk";
alter table "multiple_choice_answers" drop constraint "multiple_choice_answers__owner_fk";
alter table "multiple_choice_answers" drop constraint "multiple_choice_answers__id_fk";
alter table "multiple_choice_answers" drop constraint "multiple_choice_answers__question_fk";
alter table "multiple_choice_question_2_quiz" drop constraint "multiple_choice_question_2_quiz__question_fk";
alter table "multiple_choice_question_2_quiz" drop constraint "multiple_choice_question_2_quiz__quiz_fk";
alter table "multiple_choice_question_options" drop constraint "multiple_choice_question_options__question_id_fk";
alter table "multiple_choice_questions" drop constraint "multiple_choice_questions__owner_fk";
alter table "multiple_choice_questions" drop constraint "multiple_choice_questions__id_fk";
alter table "multiple_function_answer_options" drop constraint "multiple_function_answer_options__answer_id_fk";
alter table "multiple_function_answers" drop constraint "multiple_function_answers__owner_fk";
alter table "multiple_function_answers" drop constraint "multiple_function_answers__id_fk";
alter table "multiple_function_answers" drop constraint "multiple_function_answers__question_fk";
alter table "multiple_function_question_2_quiz" drop constraint "multiple_function_question_2_quiz__question_fk";
alter table "multiple_function_question_2_quiz" drop constraint "multiple_function_question_2_quiz__quiz_fk";
alter table "multiple_function_question_options" drop constraint "multiple_function_question_options__question_id_fk";
alter table "multiple_function_questions" drop constraint "multiple_function_questions__owner_fk";
alter table "multiple_function_questions" drop constraint "multiple_function_questions__id_fk";
alter table "polynomial_zone_answers" drop constraint "polynomial_zone_answers__owner_fk";
alter table "polynomial_zone_answers" drop constraint "polynomial_zone_answers__id_fk";
alter table "polynomial_zone_answers" drop constraint "polynomial_zone_answers__question_fk";
alter table "polynomial_zone_question_2_quiz" drop constraint "polynomial_zone_question_2_quiz__question_fk";
alter table "polynomial_zone_question_2_quiz" drop constraint "polynomial_zone_question_2_quiz__quiz_fk";
alter table "polynomial_zone_questions" drop constraint "polynomial_zone_questions__owner_fk";
alter table "polynomial_zone_questions" drop constraint "polynomial_zone_questions__id_fk";
alter table "quizzes" drop constraint "quizzes__owner_fk";
alter table "tangent_answers" drop constraint "tangent_answers__owner_fk";
alter table "tangent_answers" drop constraint "tangent_answers__id_fk";
alter table "tangent_answers" drop constraint "tangent_answers__question_fk";
alter table "tangent_question_2_quiz" drop constraint "tangent_question_2_quiz__question_fk";
alter table "tangent_question_2_quiz" drop constraint "tangent_question_2_quiz__quiz_fk";
alter table "tangent_questions" drop constraint "tangent_questions__owner_fk";
alter table "tangent_questions" drop constraint "tangent_questions__id_fk";
alter table "users_2_courses" drop constraint "users_2_courses__user_fk";
alter table "users_2_courses" drop constraint "users_2_courses__course_fk";
alter table "users_2_quizzes" drop constraint "users_2_quizzes__quiz_fk";
alter table "users_2_quizzes" drop constraint "users_2_quizzes__user_fk";
drop table "alert_game_completed";
drop table "answer_id";
drop table "application_users";
drop table "courses";
alter table "courses_2_quizzes" drop constraint "courses_2_quizzes__pk";
drop table "courses_2_quizzes";
drop table "derivative_answers";
drop table "derivative_graph_answers";
drop table "derivative_graph_question_2_quiz";
drop table "derivative_graph_questions";
drop table "derivative_question_2_quiz";
drop table "derivative_questions";
alter table "friends" drop constraint "friends__primary_key";
drop table "friends";
drop table "games";
drop table "graph_match_answers";
drop table "graph_match_questions";
drop table "graph_match_questions_2_quiz";
drop table "multiple_choice_answers";
drop table "multiple_choice_question_2_quiz";
drop table "multiple_choice_question_options";
drop table "multiple_choice_questions";
drop table "multiple_function_answer_options";
drop table "multiple_function_answers";
drop table "multiple_function_question_2_quiz";
drop table "multiple_function_question_options";
drop table "multiple_function_questions";
drop table "organizations";
drop table "polynomial_zone_answers";
drop table "polynomial_zone_question_2_quiz";
drop table "polynomial_zone_questions";
drop table "question_id";
drop table "quizzes";
drop table "secure_social_logins";
drop table "secure_social_tokens";
drop table "tangent_answers";
drop table "tangent_question_2_quiz";
drop table "tangent_questions";
alter table "users_2_courses" drop constraint "users_2_courses_pk";
drop table "users_2_courses";
alter table "users_2_quizzes" drop constraint "users_2_quizzes__pk";
drop table "users_2_quizzes";

